### ISSUE TITLE
Pixelated line-art image for mobile view in "What is SFD Page".

### ISSUE THREAD

**Issue by Dilantha-Wijesinghe** [fossnsbm/sfd2023-web#26]
The line-art image seems to be slightly pixelated when compared to the other elements in the page in mobile view. This could be due to it's larger size. I propose that the image should be made smaller in mobile view to maintain the clarity and consistency of the page.

![What is SFD page](https://github.com/fossnsbm/sfd2023-web/assets/118370653/ca1e1291-3011-4621-a47e-50708bfa772e)

**Comment by Shenon69** [comment]
The reason was that image wasn't responsive and now Its fixed.
